---
sudo: required
services:
  - docker

before_install:
  - docker build -t cedrikaagaard/memsave-frontend-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true cedrikaagaard/memsave-frontend-test npm test

after_success:
  - docker build -t cedrikaagaard/memsave-frontend ./frontend
  - docker build -t cedrikaagaard/memsave-api ./api
  - docker build -t cedrikaagaard/memsave-router ./router

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cedrikaagaard/memsave-frontend
  - docker push cedrikaagaard/memsave-api
  - docker push cedrikaagaard/memsave-router
  # Take those images and push them to docker hub

deploy:
  provider: script
  script: bash deploy-test.sh
  on:
    branch: test

# safe list
branches:
  only:
    - test
