---
sudo: required
services:
  - docker

before_install:
  - docker build -t cedrikaagaard/memsave-frontend-test -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true cedrikaagaard/memsave-frontend-test npm test

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: memsave
  env: Memsave-compose
  bucket_name: elasticbeanstalk-eu-north-1-872583650794
  bucket_path: memsave-compose
  on:
    branch: test
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

# safe list
branches:
  only:
    - master
    - test