version: '3'
services:
  postgres:
    image: 'postgres:latest'
  router:
    restart: always
    image: cedrikaagaard/memsave-router
    ports:
      - '80:80'
  frontend:
    image: cedrikaagaard/memsave-frontend
  api:
    image: cedrikaagaard/memsave-api